# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The mod license
license="DSMSL (DON'T SNATCH MA STUFF LICENSE)"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="panoramica" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="1.2.0" #mandatory
 # A display name for the mod
displayName="Panoramica" #mandatory
# A text field displayed in the mod UI
authors="Keksuccino" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Panorama Cubes - Now 16% more cuby!

Panoramica © Copyright 2020-2022 Keksuccino.
Panoramica is licensed under DSMSL (DON'T SNATCH MA STUFF LICENSE).
See the mod's GitHub for more information about this license.
'''

[[dependencies.panoramica]]
modId="konkrete"
mandatory=true
ordering="NONE"
versionRange="[1.3.2,)"
side="BOTH"

[[dependencies.panoramica]]
modId="forge"
mandatory=true
versionRange="[38.0.6,)"
ordering="NONE"
side="CLIENT"

[[dependencies.panoramica]]
modId="minecraft"
mandatory=true
versionRange="[1.18,)"
ordering="NONE"
side="CLIENT"
